
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -12;
const int acc_off_y = -231;
const int acc_off_z = 280;
// inverted so we can multiply rather than divide
const float acc_scale_x = 1.0 / 4085.264183;
const float acc_scale_y = 1.0 / 4323.495955;
const float acc_scale_z = 1.0 / 4240.195042;

const int magn_off_x = -80;
const int magn_off_y = -178;
const int magn_off_z = 98;
// inverted so we can multiply rather than divide
const float magn_scale_x = 1.0 / 515.004174;
const float magn_scale_y = 1.0 / 512.730878;
const float magn_scale_z = 1.0 / 483.091973;
